### ISSUE TITLE
There is no vbback in old ASP

### ISSUE THREAD

**Issue by flameward** [rcdmk/aspJSON#53]
My solution.

dim vbback
vbback = Chr(8)

**Comment by rcdmk** [comment]
Thank you.
I'll fix that soon.

**Comment by MarcoMiltenburg** [comment]
I think something went wrong with this fix in commit 86f0f5999586da462fe0c41540be8732b6068dc6. First of all the use of `vbback` is still in the code and the code to replace the tab character was changed in a way that causes a compilation error. `char(8)` is invalid and should be `chr(9)` (i.e. without the 'a' and '9' instead of '8').
