### ISSUE TITLE
Incorrect Time Zone handling

### ISSUE THREAD

**Issue by VNexsus** [rcdmk/aspJSON#71]
When GetTimeZoneOffset() function calculates positive offset (i.e. "+02:00") returning value does not contain "+",  so portion of code in line 693 "... & left(offset, 1) & ..." makes datetime value invalid.

It can be fixed by adding this line of code right before the end of GetTimeZoneOffset() function:
if GetTimeZoneOffset > 0 then GetTimeZoneOffset = "+" & GetTimeZoneOffset

**Comment by rcdmk** [comment]
Hello!
I'm grate you pointed this out, but I've removed the TimeZone handling from newer versions.
This classes already deal with many things and this was causing some trouble because there is no safe way to get the TZ info in all cases and there is no way to calculate the correct TZ for past or future dates.

Thanks anyway.
